### ISSUE TITLE
Server Side jobs run twice (two mounts)

### ISSUE THREAD

**Issue by bradbarrow** [ctrlplusb/react-jobs#18] opened 2017-01-30 04:56 UTC
I'm using `react-jobs` on the client and server but I'm finding that the job is executed twice on the server.

I've followed the react-jobs README and carefully read the code in the `redux-opinionated` branch of `react-universally` [here](https://github.com/ctrlplusb/react-universally/tree/feature/redux-opinionated)

The issue appears to be due to the fact that we first call `runJobs(app)` which presumably "renders" the app once, thereby running all the jobs but we then ALSO call `renderToString(appWithJobs)` which (in my case at least) runs them all again.

This seems less than ideal for performance? Is it rendering the whole tree twice? My jobs perform async data fetches via `redux-thunk`'s and I'm seeing those requests hit my API twice.

I have read the docs on the `shouldWorkAgain` config, but it appears to only be concerned with receiving props and not with the mounting of the component. So on the server, since we render twice we mount twice, and since we mount twice we run work twice. 

Is this expected?

**Comment by ctrlplusb** [comment] 2017-01-30 08:52
Hi @bradbarrow!

This is certainly not the expected behaviour. This may be a regression case. I'll beef up the tests and get back to you.

**Comment by cowwen** [comment] 2017-02-05 16:45
Hey @ctrlplusb , I found this bug too, and think it because runJobs.js use reactTreeWalker instantiating element(component with job) twice when process the  regression.
It should continue traversing from the created instance like below

jobs.push({ job, instance, context });

Hop it will be helpful. thanks.

**Comment by ctrlplusb** [comment] 2017-04-05 01:07
Hey all;

Closing this as a tree parse is expected.  

@cowwen please let me know if you experience anything similar with the new API.

**Closed by ctrlplusb** 2017-04-05 01:07 UTC
Labels: bug
